#!/usr/bin/env node
import Database from 'better-sqlite3';
import { Client } from 'pg';
import dotenv from 'dotenv';
import path from 'path';

// Usage: node server/seed_neon_from_sqlite.js [sqlitePath]
// Default sqlitePath: /home/chayes/flashcards.db

dotenv.config({ path: path.resolve(process.cwd(), '.env.local') });
dotenv.config();

const sqlitePath = process.argv[2] || '/home/chayes/flashcards.db';

function getPgConfig() {
  if (process.env.DATABASE_URL) {
    return { connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false } };
  }
  return {
    host: process.env.PGHOST || 'localhost',
    port: Number(process.env.PGPORT || 5432),
    user: process.env.PGUSER || 'flashcards',
    password: process.env.PGPASSWORD || 'flashcards',
    database: process.env.PGDATABASE || 'flashcards',
  };
}

async function seed() {
  console.log(`Reading from SQLite: ${sqlitePath}`);
  const sq = new Database(sqlitePath, { readonly: true });

  const categories = sq.prepare('SELECT id, name, created_at, updated_at FROM categories ORDER BY id').all();
  const flashcards = sq.prepare('SELECT id, category_id, front, back, back_format, created_at, updated_at FROM flashcards ORDER BY id').all();
  console.log(`Exported ${categories.length} categories and ${flashcards.length} flashcards.`);

  const client = new Client(getPgConfig());
  await client.connect();
  try {
    await client.query('BEGIN');

    // Ensure tables exist (no-op if already created)
    await client.query(`
      CREATE TABLE IF NOT EXISTS categories (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT UNIQUE NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      );
      CREATE TABLE IF NOT EXISTS flashcards (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        category_id INTEGER NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
        front TEXT NOT NULL,
        back TEXT NOT NULL,
        back_format TEXT DEFAULT 'sentence' CHECK (back_format IN ('sentence', 'list')),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      );
    `);

    // Reset current data then insert fresh
    await client.query('TRUNCATE TABLE flashcards, categories RESTART IDENTITY CASCADE');

    for (const c of categories) {
      await client.query(
        'INSERT INTO categories (id, name, created_at, updated_at) VALUES ($1, $2, $3, $4)',
        [c.id, c.name, c.created_at, c.updated_at]
      );
    }

    for (const f of flashcards) {
      await client.query(
        'INSERT INTO flashcards (id, category_id, front, back, back_format, created_at, updated_at) VALUES ($1, $2, $3, $4, $5, $6, $7)',
        [f.id, f.category_id, f.front, f.back, f.back_format || 'sentence', f.created_at, f.updated_at]
      );
    }

    // Align sequences to max id
    await client.query("SELECT setval(pg_get_serial_sequence('categories', 'id'), COALESCE((SELECT MAX(id) FROM categories), 1));");
    await client.query("SELECT setval(pg_get_serial_sequence('flashcards', 'id'), COALESCE((SELECT MAX(id) FROM flashcards), 1));");

    await client.query('COMMIT');

    const catCount = await client.query('SELECT COUNT(*)::int AS count FROM categories');
    const cardCount = await client.query('SELECT COUNT(*)::int AS count FROM flashcards');
    console.log(`Neon seed complete. categories=${catCount.rows[0].count}, flashcards=${cardCount.rows[0].count}`);
  } catch (e) {
    await client.query('ROLLBACK');
    console.error('Seeding failed:', e.message);
    process.exitCode = 1;
  } finally {
    await client.end();
  }
}

seed();
